<Project>
  <Import Project="$(MSBuildThisFileDirectory).local-dev/paths.props" Condition="Exists('$(MSBuildThisFileDirectory).local-dev/paths.props')" />
  <PropertyGroup>
    <Sts2DataDir Condition="'$(Sts2DataDir)' == '' and '$(OS)' != 'Windows_NT'">$(HOME)/Library/Application Support/Steam/steamapps/common/Slay the Spire 2/SlayTheSpire2.app/Contents/Resources/data_sts2_macos_x86_64</Sts2DataDir>
    <BaseLibPath Condition="'$(BaseLibPath)' == '' and Exists('$(MSBuildThisFileDirectory)../mods/BaseLib/BaseLib.dll')">$(MSBuildThisFileDirectory)../mods/BaseLib/BaseLib.dll</BaseLibPath>
    <BaseLibPath Condition="'$(BaseLibPath)' == ''">$(MSBuildThisFileDirectory)../BaseLib.dll</BaseLibPath>
  </PropertyGroup>
</Project>
